framework:
    messenger:
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    use_notify: true
                    check_delayed_interval: 60000
                retry_strategy:
                    max_retries: 3
                    multiplier: 2
            failed: 'doctrine://default?queue_name=failed'
            sync: 'sync://'

        # CQRS Configuration with separate buses
        default_bus: command.bus
        
        buses:
            # Command Bus - for state changes
            command.bus:
                middleware:
                    - validation
                    - doctrine_transaction
            
            # Query Bus - for data retrieval
            query.bus:
                middleware:
                    - validation

        routing:
            # Email and notification routing (keep existing async)
            Symfony\Component\Mailer\Messenger\SendEmailMessage: async
            Symfony\Component\Notifier\Message\ChatMessage: async
            Symfony\Component\Notifier\Message\SmsMessage: async

            # CQRS routing - all synchronous for this project
            'App\Application\Command\*': sync
            'App\Application\Query\*': sync
