services:
    # Roles dictionary provider using RolesEnum
    app.dictionary.provider.roles:
        class: App\Dictionary\Provider\EnumDictionaryProvider
        arguments:
            $type: 'roles'
            $enumClass: 'App\Enum\RolesEnum'

    # Tax Status dictionary provider using TaxStatusEnum
    app.dictionary.provider.tax_status:
        class: App\Dictionary\Provider\EnumDictionaryProvider
        arguments:
            $type: 'tax_status'
            $enumClass: 'App\Enum\TaxStatusEnum'

    # Dictionary Registry is configured via compiler pass (see DictionaryProviderPass)